//Name: MPUS
//Assignment: Project Bruteforce
//Date: 03/20/17
//Purpose: demonstrate how to bruteforce a password sequentially


#include<mpi.h>
#include<stdio.h>
#include<stdlib.h>
#include<string.h>

//Prototypes
int pwdCheck(char *password); 
void recursion(int width, int pos, char *base);

//Global Variables
#define MAXCHAR 10 //for simplicity, limit pasword character count to 10, time increases alot with additional characters
char pwd[MAXCHAR] = "bread"; //password user enters
int printCount = 0; //recurive print control

//array holds numbers 0-9 and lowercase characters
char chars[] = {'0','1','2','3','4','5','6','7','8','9','a','b','c',
'd','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t',
'u','v','w','x','y','z'};

void main()
{
	int size, rank;
	int i = 0; //loop control variable 
	
	//declares empty string to be appended to character in chars array on each iteration
	//C strings are stored as array of chars
	char base[MAXCHAR] = ""; 
	
	//timing variables
	double start = 0;
	double end = 0;
	
	MPI_Init(NULL,NULL); //initialize MPI
	MPI_Comm_size(MPI_COMM_WORLD, &size); //get number of processes
	MPI_Comm_rank(MPI_COMM_WORLD, &rank); //get process rank
	
	//start timing calculations here
	start = MPI_Wtime();
	
	//loop to check each character in string up to MAXCHAR of user password characters
	for(i = 1; i < MAXCHAR; i++)
	{
		recursion(i,0,base);
	}  
	//end timing 
	end = MPI_Wtime();
	
	printf("\nTime Elapsed = %f seconds\n", end-start);	
	
	MPI_Finalize();
}

//Purpose: compares the user's password against the string generated by the program
//Requires: the string generated by the program
//Returns: none, checks to see if the 2 passwords are equal
int pwdCheck(char *password)
{
	if(strcmp(password,pwd) == 0) //compare the 2 strings using strcmp function
	{
		return 1;
	}
	else return 0;
}

//Purpose: generates the string that is checked against the user's password recursively
//Requires: the width of the user's password, the position in the string, number of elements in chars array
//Returns: none
void recursion(int width, int pos, char *base)
{
	int i = 0;
	
	
	//loop through characters in chars array
	for(i = 0; i < 35; i++)
	{
		if (pwdCheck(base) == 1)
		{
			
			if (printCount  == 0)
			{
				printf("\nPassword Match, Password = %s",base);
				printCount++;
			}
			return;
		}
		if(pos < width-1) //checks to ensure that 'cursor' doesn't go beyond length of the string
		{
			base[pos] = chars[i]; //appends the character from the chars array to the generated string
			recursion(width, pos+1,base); //continues recursive call with new string
		}
	}
}
